---
- hosts: all
  become: yes
  tasks:
    - name: Turn on SWAP
      shell: |
        swapon -a
      ignore_errors: yes

    - name: Remove worker node from the cluster (only if worker)
      command: kubeadm reset -f
      when: "'worker' in inventory_hostname"

    - name: Remove Kubernetes components (on all nodes)
      apt:
        name: kubelet,kubeadm,kubectl
        state: absent

    - name: Remove Containerd (on all nodes)
      apt:
        name: containerd.io
        state: absent

    - name: Remove Docker (if used) - Customize this task based on your container runtime
      apt:
        name: docker-ce
        state: absent
      ignore_errors: yes

    - name: Remove Kubernetes configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes/
        - ~/.kube/

    - name: Delete Flannel CNI resources (only if Flannel was installed)
      shell: kubectl delete -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      ignore_errors: yes
      when: "'master' in inventory_hostname"
