---
- hosts: all
  tasks:
    - name: Remove Flannel CNI
      shell: kubectl delete daemonsets -n kube-system kube-flannel-ds-amd64
      ignore_errors: yes

    - name: Delete Flannel CNI resources
      shell: kubectl delete -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      ignore_errors: yes

    - name: Reset Kubernetes on Master and Worker nodes
      shell: kubeadm reset -f
      when: "'master' in inventory_hostname or 'worker' in inventory_hostname"

    - name: Uninstall Containerd
      apt:
        name: containerd.io
        state: absent

    # Add tasks to remove Docker or other container runtimes if used.

    - name: Uninstall Kubernetes components
      apt:
        name: kubelet,kubeadm,kubectl
        state: absent

    - name: Remove Kubernetes configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes/
        - ~/.kube/

    - name: Uninstall kubectl
      apt:
        name: kubectl
        state: absent

    - name: Reboot the nodes
      command: reboot
      async: 0
      poll: 0
      when: "'master' in inventory_hostname or 'worker' in inventory_hostname"

# Optionally, you can add more tasks to remove additional components or configurations specific to your setup.
